# Generated by Django 4.1.3 on 2023-03-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='lname',
        ),
    ]
