# Generated by Django 4.1.3 on 2023-03-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_rename_fname_pessoa_name_remove_pessoa_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.IntegerField(max_length=11)),
            ],
        ),
    ]
