# Generated by Django 4.1.3 on 2023-03-14 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='cpf',
        ),
    ]
