# Generated by Django 4.1.3 on 2023-03-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_registro_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
