# Generated by Django 4.1.3 on 2023-03-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0008_delete_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='registration',
            field=models.DateField(null=True),
        ),
    ]
