# Generated by Django 4.1.3 on 2023-03-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0009_pessoa_cpf_pessoa_email_pessoa_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='registration',
            new_name='bornDate',
        ),
    ]
